INSERT INTO public.woa_products (id, ar, en, price, category_id, usage_type, usage_ar, usage_en, image) VALUES
(511, 'ترولي زجاجي الماني 40سم نيسكو', 'ترولي زجاجي الماني 40cm نيسكو', '4400', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(512, 'مفصلة اوميجا عدلة فضي 3D سوفت كلوز', 'Hinge اوميجا Straight فضي 3D Soft Close', '28', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(513, 'مفصلة اوميجا نص ركبه فضي 3D سوفت كلوز', 'Hinge اوميجا نص ركبه فضي 3D Soft Close', '28', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(514, 'مفصلة اوميجا عدلة اسود 3D سوفت كلوز', 'Hinge اوميجا Straight Black 3D Soft Close', '30', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(515, 'مفصلة اوميجا نص ركبه اسود 3D سوفت كلوز', 'Hinge اوميجا نص ركبه Black 3D Soft Close', '30', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(516, 'مقبض بلت ان هوك 30سم مستورد جديد اسود', 'Handle بلت ان هوك 30cm مستورد جديد Black', '43', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(517, 'مطبقيه هيدروليك بالما 60 سم فضي', 'مطبقيه هيدروليك Palma 60 cm فضي', '3650', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(518, 'مطبقيه هيدروليك بالما 70سم فضي', 'مطبقيه هيدروليك Palma 70cm فضي', '3800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(519, 'مطبقيه هيدروليك بالما 80سم فضي', 'مطبقيه هيدروليك Palma 80cm فضي', '3900', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(520, 'رشاقه خزان باور بالما 80 سم فضي', 'رشاقه خزان باور Palma 80 cm فضي', '6800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(521, 'مطبقيه درج 70سم ع مجرى سفلي ( اسود) palma', 'مطبقيه Drawer 70cm ع Runner/Slide سفلي ( Black) palma', '2100', 3, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_undermount.jpg'),
(522, 'مطبقيه درج 90سم ع مجرى سفلي ( اسود) palma', 'مطبقيه Drawer 90cm ع Runner/Slide سفلي ( Black) palma', '2300', 3, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_undermount.jpg'),
(523, 'كعب زاويه 90 ابيض', 'كعب Angle 90 White', '1.5', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(524, 'كعب زاويه 90 بني', 'كعب Angle 90 بني', '1.5', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(525, 'كعب عدل بني', 'كعب عدل بني', '1', 6, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(526, 'ترولي مودرن سوفت كلوز 30سم', 'ترولي مودرن Soft Close 30cm', '1680', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(527, 'مجرى جانبي سوفت كلوز بالما 30 سم', 'Runner/Slide جانبي Soft Close Palma 30 cm', '180', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(528, 'مجرى جانبي سوفت كلوز بالما 35 سم', 'Runner/Slide جانبي Soft Close Palma 35 cm', '190', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(529, 'مجرى جانبي سوفت كلوز بالما 40 سم', 'Runner/Slide جانبي Soft Close Palma 40 cm', '200', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(530, 'مجرى جانبي سوفت كلوز بالما 45 سم', 'Runner/Slide جانبي Soft Close Palma 45 cm', '210', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(531, 'مجرى جانبي سوفت كلوز بالما 50 سم', 'Runner/Slide جانبي Soft Close Palma 50 cm', '220', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(532, 'درج مطبخ زجاج سوفت كلوز 60سم بالما', 'Drawer مطبخ زجاج Soft Close 60cm Palma', '2400', 3, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_ball_bearing.jpg'),
(533, 'حامل طاسات اسود سوفت بالما', 'حامل طاسات Black سوفت Palma', '1600', 9, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(534, 'خزنة تربو 20سم', 'خزنة تربو 20cm', '1400', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_safe_dressing.jpg'),
(535, 'دراع منطبق افنتوس دانكو 2 ضلفه', 'Arm منطبق افنتوس دانكو 2 ضلفه', '1520', 4, 'other', 'أخرى', 'Other', 'assets/products/preset_gas_strut.jpg'),
(536, 'مسمار ديكور مخفى', 'مcmار ديكور مخفى', '50', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(537, 'مفصله باب بيانو 177 ملي دانكو 3D', 'Hinge باب بيانو 177 mm دانكو 3D', '520', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(538, 'ميكانيزم باب مخفي 150 سم mk', 'ميكانيزم باب مخفي 150 cm mk', '2850', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(539, 'بصمه معدن دهبي', 'بصمه معدن دهبي', '5', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(540, 'مسمار تجميع معدن', 'مcmار تجميع معدن', '5', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(541, 'مطبقیه 70سم سوسته الحياة', 'مطبقیه 70cm سوسته الحياة', '850', 8, 'other', 'أخرى', 'Other', 'assets/products/preset_dish_rack_lift.jpg'),
(542, 'هوايه بلاستيك مطبخ 8*25 اسود', 'هوايه بلاستيك مطبخ 8*25 Black', '30', 6, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_vent_grille.jpg'),
(543, 'هوايه بلاستيك مطبخ 8*25 رماد', 'هوايه بلاستيك مطبخ 8*25 رماد', '30', 6, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_vent_grille.jpg'),
(544, 'هوايه بلاستيك مطبخ 8*25 ابيض', 'هوايه بلاستيك مطبخ 8*25 White', '30', 6, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_vent_grille.jpg'),
(545, 'كالون درج مكتب زور طويل', 'Lock Drawer مكتب زور طويل', '85', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(546, 'كالون درج مكتب زور قصير', 'Lock Drawer مكتب زور قصير', '80', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(547, 'تقسيمة درج 35 سم مصري', 'Dividerة Drawer 35 cm مصري', '130', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(548, 'تقسيمة درج 40 سم مصري', 'Dividerة Drawer 40 cm مصري', '140', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(549, 'تقسيمة درج 45 سم مصري', 'Dividerة Drawer 45 cm مصري', '150', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(550, 'تقسيمة درج 50 سم مصري', 'Dividerة Drawer 50 cm مصري', '165', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(551, 'تقسيمة درج 55 سم مصري', 'Dividerة Drawer 55 cm مصري', '175', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(552, 'تقسيمة درج 60 سم مصري', 'Dividerة Drawer 60 cm مصري', '185', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(553, 'تقسيمة درج 70 سم مصري', 'Dividerة Drawer 70 cm مصري', '210', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(554, 'قطاع دريسنج زجاج بمقبض صغير عدل اسود الكترو بلوم', 'قطاع دريسنج زجاج بHandle صغير عدل Black الكترو بلوم', '600', 2, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_handle_bar_black.jpg'),
(555, 'باسكت 16 لتر STARA-X', 'باسكت 16 لتر STARA-X', '2100', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_waste_bin.jpg'),
(556, 'باسكت 24 لتر STARA-X', 'باسكت 24 لتر STARA-X', '2450', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_waste_bin.jpg'),
(557, 'باسكت 10 لتر STARA-X محوري', 'باسكت 10 لتر STARA-X محوري', '950', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_waste_bin.jpg'),
(558, 'مجرى جانبي تاتش 45 سم مودرن', 'Runner/Slide جانبي تاتش 45 cm مودرن', '190', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(559, 'مقبض بلت ان هوك 30سم مستورد جديد فضي', 'Handle بلت ان هوك 30cm مستورد جديد فضي', '40', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(560, 'مقبض بلت ان هوك 20سم مستورد جديد فضي', 'Handle بلت ان هوك 20cm مستورد جديد فضي', '32', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(561, 'مقبض بصمه بلاستيك 10سم اسود', 'Handle بصمه بلاستيك 10cm Black', '6', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(562, 'مقبض عدل 13سم اسود بلاستيك', 'Handle عدل 13cm Black بلاستيك', '10', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(563, 'هوايه مطبخ 20*6 اسود', 'هوايه مطبخ 20*6 Black', '30', 6, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_vent_grille.jpg'),
(564, 'فوم اسطا تركي', 'فوم اسطا Turkish', '145', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(565, 'ترابيزه مكوه سوفت کلوز  كاف', 'ترابيزه مكوه سوفت کلوز  كاف', '3150', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(566, 'شماعة بناطيل علوية مجوز  نبيتي سوفت كلوز كاف', 'شماعة بناطيل علوية مجوز  نبيتي Soft Close كاف', '3400', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(567, 'مجرى درج 50سم تاندم بوكس  samet', 'Runner/Slide Drawer 50cm تاندم بوكس  samet', '1250', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_tandem.jpg'),
(568, 'ميكانيزم سرير 120   برنس', 'ميكانيزم سرير 120   برنس', '700', 4, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(569, 'ميكانيزم سرير 150برنس', 'ميكانيزم سرير 150برنس', '770', 4, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(570, 'خزنة تربو 30سم', 'خزنة تربو 30cm', '2500', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_safe_dressing.jpg'),
(571, 'مفصله عقربه مودرن 2D', 'Hinge Scorpion مودرن 2D', '60', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(572, 'مسمار تربو 5سم ابيض', 'مcmار تربو 5cm White', '97', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(573, 'مقبض بلت ان هوك 128مم اسود جديد', 'Handle بلت ان هوك 128مم Black جديد', '17', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(574, 'خزنة تربو 30سم ارقام وشاشة', 'خزنة تربو 30cm ارقام وشاشة', '3700', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_safe_dressing.jpg'),
(575, 'مقبض بلت ان هوك 16سم مستورد جديد اسود', 'Handle بلت ان هوك 16cm مستورد جديد Black', '22', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(576, 'مكينة عد النقود', 'مكينة عد النقود', '4200', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(577, 'كعب كرسي 20 ملي بني', 'كعب كرسي 20 mm بني', '1.2', 6, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(578, 'ترولي بارما تركى 35سم', 'ترولي بارما تركى 35cm', '2950', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(579, 'j;hdi', 'j;hdi', '0', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(580, 'دولاب محوري 6رف اكلريك 45سم', 'دولاب محوري 6Shelf اكلريك 45cm', '8800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(581, 'مفصله روما عدله3d', 'Hinge روما عدله3d', '22', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(582, 'مفصله روما عقربه3d', 'Hinge روما Scorpion3d', '65', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(583, 'علاقه مطبخ رجلاش ابيض', 'علاقه مطبخ Adjustable White', '24', 2, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_cabinet_legs.jpg'),
(584, 'خزنة دريسنج رقمية 60 سم بدون تقسيم', 'خزنة دريسنج رقمية 60 cm بدون Divider', '6600', 10, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_safe_dressing.jpg'),
(585, 'درج اكسسوارات متحرك جراي', 'Drawer Accessories Movable Grey', '3100', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(586, 'درج اكسسوارات متحرك اورانج', 'Drawer Accessories Movable Orange', '3100', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(587, 'درج تقسيم اكسسوارات 70 سم بالما اورنج', 'Drawer Divider Accessories 70 cm Palma Orange', '3800', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(588, 'درج تقسيم اكسسوارات 70 سم بالما جراي', 'Drawer Divider Accessories 70 cm Palma Grey', '3800', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(589, 'درج تقسيم اكسسوارات 80 سم بالما جراي مع غطاء', 'Drawer Divider Accessories 80 cm Palma Grey مع غطاء', '4200', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(590, 'درج تخليه تحت الحوض 80سم', 'Drawer تخليه تحت الSink 80cm', '2500', 3, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_ball_bearing.jpg')
ON CONFLICT (id) DO UPDATE SET ar=EXCLUDED.ar, en=EXCLUDED.en, price=EXCLUDED.price, category_id=EXCLUDED.category_id, usage_type=EXCLUDED.usage_type, usage_ar=EXCLUDED.usage_ar, usage_en=EXCLUDED.usage_en, image=EXCLUDED.image;