INSERT INTO public.woa_products (id, ar, en, price, category_id, usage_type, usage_ar, usage_en, image) VALUES
(351, 'ترولي 16 اسود عادي 3R', 'ترولي 16 Black عادي 3R', '840', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(352, 'ترولي 20 اسود عادي 3R', 'ترولي 20 Black عادي 3R', '850', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(353, 'ترولي 25 اسود عادي 3R', 'ترولي 25 Black عادي 3R', '860', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(354, 'دراع باكم تاج ضغط 80', 'Arm Hydraulic تاج ضغط 80', '20', 4, 'other', 'أخرى', 'Other', 'assets/products/preset_gas_strut.jpg'),
(355, 'مجرى 30جانبي سوفت FGV ايطالي', 'Runner/Slide 30جانبي سوفت FGV ايطالي', '240', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(356, 'مجرى 35جانبي سوفت FGV ايطالي', 'Runner/Slide 35جانبي سوفت FGV ايطالي', '250', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(357, 'مجرى 40جانبي سوفت FGV ايطالي', 'Runner/Slide 40جانبي سوفت FGV ايطالي', '260', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(358, 'مجرى 45جانبي سوفت FGV ايطالي', 'Runner/Slide 45جانبي سوفت FGV ايطالي', '270', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(359, 'مجرى 50جانبي سوفت FGV ايطالي', 'Runner/Slide 50جانبي سوفت FGV ايطالي', '280', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(360, 'كرت بصمة', 'كرت بصمة', '10', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(361, 'مفصله اندوكس اسباني عدلة سوفت فرش 4 مسمار', 'Hinge اندوكس اسباني Straight سوفت فرش 4 مcmار', '48', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(362, 'مفصله 3Dدانكو عدلة سوفت كلوز', 'Hinge 3Dدانكو Straight Soft Close', '27', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(363, 'مفصله 3Dدانكو نص ركبة سوفت كلوز', 'Hinge 3Dدانكو Half Overlay Soft Close', '27', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(364, 'مفصله 3Dدانكو ركبة كاملة سوفت كلوز', 'Hinge 3Dدانكو Full Overlay Soft Close', '27', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(365, 'مجرى دنكو 25سم جانبيه سوفت كلوز', 'Runner/Slide دنكو 25cm جانبيه Soft Close', '145', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(366, 'مجرى دنكو 30سم جانبيه سوفت كلوز', 'Runner/Slide دنكو 30cm جانبيه Soft Close', '155', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(367, 'مجرى دنكو 35سم جانبيه سوفت كلوز', 'Runner/Slide دنكو 35cm جانبيه Soft Close', '165', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(368, 'مجرى دنكو 40سم جانبيه سوفت كلوز', 'Runner/Slide دنكو 40cm جانبيه Soft Close', '175', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(369, 'مجرى دنكو 45سم جانبيه سوفت كلوز', 'Runner/Slide دنكو 45cm جانبيه Soft Close', '185', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(370, 'عود وزر 15 سم اسود', 'عود وزر 15 cm Black', '485', 6, 'other', 'أخرى', 'Other', 'assets/products/preset_edge_trim.jpg'),
(371, 'زاويه وزره متحركه 10سم اسود', 'Angle وزره Movableه 10cm Black', '28', 6, 'other', 'أخرى', 'Other', 'assets/products/preset_edge_trim.jpg'),
(372, 'قطاع زجاج بدون مقبض دهبي3 م', 'قطاع زجاج بدون Handle دهبي3 م', '250', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(373, 'قطاع زجاج بمقبض دهبي3 م', 'قطاع زجاج بHandle دهبي3 م', '270', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(374, 'ماده تركي سريع Usta 400', 'ماده Turkish سريع Usta 400', '95', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(375, 'ميكانيزم جزامة أبيض', 'ميكانيزم جزامة أبيض', '90', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(376, 'درج ملابس 80سم زجاج بمجرى سفلي سوفت كلوز بالما', 'Drawer ملابس 80cm زجاج بRunner/Slide سفلي Soft Close Palma', '3250', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_undermount.jpg'),
(377, 'درج ملابس 90سم زجاج بمجرى سفلي سوفت كلوز بالما', 'Drawer ملابس 90cm زجاج بRunner/Slide سفلي Soft Close Palma', '3350', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_undermount.jpg'),
(378, 'ماجيك فاصوليا المونيوم عالى 45 سم شمال بالما', 'ماجيك فاصوليا المونيوم عالى 45 cm شمال Palma', '4500', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(379, 'ماجيك فاصوليا المونيوم عالى 45 سم يمين بالما', 'ماجيك فاصوليا المونيوم عالى 45 cm يمين Palma', '4500', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(380, 'تكايه رف زجاج ببنز بلاستك', 'تكايه Shelf زجاج ببنز بلاستك', '7.5', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(381, 'ليد بروفايل وسط بدون شفه', 'LED Profile وسط بدون شفه', '100', 6, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(382, 'ليد بروفايل وسط بشفه', 'LED Profile وسط بشفه', '100', 6, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(383, 'بروفيل 240 ورم سويدي', 'بروفيل 240 ورم سويدي', '190', 6, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(384, 'وصلة بروفايل بالسلك', 'وصلة Profile بالWire', '15', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(385, 'وصلة بروفايل بدون سلك', 'وصلة Profile بدون Wire', '10', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(386, 'حامل مكواه STARA-X', 'حامل مكواه STARA-X', '650', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(387, 'ترولي جانبي 30 سم فضي بقاعدة خشبية palm', 'ترولي جانبي 30 cm فضي بقاعدة خشبية palm', '1750', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(388, 'ترولي جانبي 30 سم اسود بقاعدة خشبية palm', 'ترولي جانبي 30 cm Black بقاعدة خشبية palm', '1800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(389, 'ترولي جانبي 35سم فضي بقاعدة خشبية palm', 'ترولي جانبي 35cm فضي بقاعدة خشبية palm', '1800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(390, 'ترولي جانبي 35 سم اسود بقاعدة خشبية palm', 'ترولي جانبي 35 cm Black بقاعدة خشبية palm', '1880', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(391, 'خزنة دريسنج رقمية 50سم ( مقسمة )', 'خزنة دريسنج رقمية 50cm ( مقcmة )', '6200', 10, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_safe_dressing.jpg'),
(392, 'ترولي المونيوم ع مجرى سفلي 30سم', 'ترولي المونيوم ع Runner/Slide سفلي 30cm', '4150', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_undermount.jpg'),
(393, 'ترولي المونيوم ع مجرى سفلي 35سم', 'ترولي المونيوم ع Runner/Slide سفلي 35cm', '4300', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_undermount.jpg'),
(394, 'ترولي المونيوم ع مجرى سفلي 40سم', 'ترولي المونيوم ع Runner/Slide سفلي 40cm', '4400', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_undermount.jpg'),
(395, 'شماعة بدل هيدروليك 10 كيلو تركي STAR-X', 'شماعة بدل هيدروليك 10 كيلو Turkish STAR-X', '1900', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(396, 'شماعة بدل هيدروليك 15 كيلو تركي STAR-X', 'شماعة بدل هيدروليك 15 كيلو Turkish STAR-X', '1950', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(397, 'درج حامل بناطيل 70سم اورنج', 'Drawer حامل بناطيل 70cm Orange', '2500', 3, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_drawer_ball_bearing.jpg'),
(398, 'درج حامل بناطيل 80سم جراي', 'Drawer حامل بناطيل 80cm Grey', '2600', 3, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_drawer_ball_bearing.jpg'),
(399, 'درج حامل بناطيل 80سم اورنج', 'Drawer حامل بناطيل 80cm Orange', '2600', 3, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_drawer_ball_bearing.jpg'),
(400, 'درج حامل بناطيل 90سم اورنج', 'Drawer حامل بناطيل 90cm Orange', '2700', 3, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_drawer_ball_bearing.jpg'),
(401, 'درج حامل بناطيل 90سم جراي', 'Drawer حامل بناطيل 90cm Grey', '2700', 3, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_drawer_ball_bearing.jpg'),
(402, 'درج احذية 70سم سوفت كلوز بالما', 'Drawer احذية 70cm Soft Close Palma', '3000', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(403, 'درج احذية 80سم سوفت كلوز بالما', 'Drawer احذية 80cm Soft Close Palma', '3350', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(404, 'درج حامل بناطيل 70سم جراي', 'Drawer حامل بناطيل 70cm Grey', '2500', 3, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_drawer_ball_bearing.jpg'),
(405, 'جزامة محورية 6 رف بالما', 'جزامة محورية 6 Shelf Palma', '6150', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(406, 'جزامة محورية 8رف بالما', 'جزامة محورية 8Shelf Palma', '6900', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(407, 'طقم درج زجاج 80سم (2 درج مطبخ ) بالما', 'طقم Drawer زجاج 80cm (2 Drawer مطبخ ) Palma', '5460', 3, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_ball_bearing.jpg'),
(408, 'ماجيك كورنر حصان 45سم فضي مودرن', 'ماجيك كورنر حصان 45cm فضي مودرن', '5100', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(409, 'ترولي جانبي 20سم فضي بقاعدة خشبية palm', 'ترولي جانبي 20cm فضي بقاعدة خشبية palm', '1500', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(410, 'ترولي جانبي 25سم فضي بقاعدة خشبية palm', 'ترولي جانبي 25cm فضي بقاعدة خشبية palm', '1600', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(411, 'دولاب محوري 2 رف زجاج 60سم بالما سوفت كلوز', 'دولاب محوري 2 Shelf زجاج 60cm Palma Soft Close', '2950', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(412, 'دولاب دريسنج كورنر 4 دور بالما (3كرتونه )', 'دولاب دريسنج كورنر 4 دور Palma (3كرتونه )', '7850', 5, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(413, 'دولاب دريسنج كورنر 3دور ارفف بالما (3كرتونه )', 'دولاب دريسنج كورنر 3دور اShelfف Palma (3كرتونه )', '7750', 5, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(414, 'دولاب دريسنج كورنر 3 دور بالما (كرتونه )', 'دولاب دريسنج كورنر 3 دور Palma (كرتونه )', '5650', 5, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(415, 'دولاب دريسنج كورنر 2دور بالما (كرتونه )', 'دولاب دريسنج كورنر 2دور Palma (كرتونه )', '4350', 5, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(416, 'دولاب محوري 6رف استانلس 45سم اسود بالما سوفت كلوز', 'دولاب محوري 6Shelf استانلس 45cm Black Palma Soft Close', '7300', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(417, 'شماعة بدل هيدروليك بالما', 'شماعة بدل هيدروليك Palma', '1350', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(418, 'ماجيك كورنر حصان 45سم زجاج معدل بالما', 'ماجيك كورنر حصان 45cm زجاج معدل Palma', '6100', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(419, 'كارجو 6 رف 45سم زجاج سوفت كلوز بالما', 'كارجو 6 Shelf 45cm زجاج Soft Close Palma', '8200', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(420, 'مطبقيه درج رمادي مقسم الماني 70سم', 'مطبقيه Drawer رمادي مقcm الماني 70cm', '5500', 3, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_ball_bearing.jpg'),
(421, 'مطبقيه درج رمادي مقسم الماني 80سم', 'مطبقيه Drawer رمادي مقcm الماني 80cm', '5800', 3, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_drawer_ball_bearing.jpg'),
(422, 'مجرى سفليه سوفت كلوز 35سم نيسكو', 'Runner/Slide سفليه Soft Close 35cm نيسكو', '450', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_undermount.jpg'),
(423, 'رشاقه خزان الماني 70سم', 'رشاقه خزان الماني 70cm', '7200', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(424, 'مجرى ساميت 50سم جانبي', 'Runner/Slide Summit 50cm جانبي', '470', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(425, 'حامل طاسات نيسكو', 'حامل طاسات نيسكو', '1900', 9, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(426, 'ماجيك فاصوليا المونيوم  الماني يمين نيسكو', 'ماجيك فاصوليا المونيوم  الماني يمين نيسكو', '10800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(427, 'ماجيك فاصوليا المونيوم  الماني شمال نيسكو', 'ماجيك فاصوليا المونيوم  الماني شمال نيسكو', '10800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(428, 'ماجيك كورنر حصان ارضيه خشبيه ابيض نيسكو', 'ماجيك كورنر حصان ارضيه خشبيه White نيسكو', '7150', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(429, 'شماعه هيدروليك 80سم نيسكو', 'Hanger هيدروليك 80cm نيسكو', '2950', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(430, 'شماعه بناطيل زوجي مضئ 70سم نيسكو', 'Hanger بناطيل زوجي مضئ 70cm نيسكو', '4800', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg')
ON CONFLICT (id) DO UPDATE SET ar=EXCLUDED.ar, en=EXCLUDED.en, price=EXCLUDED.price, category_id=EXCLUDED.category_id, usage_type=EXCLUDED.usage_type, usage_ar=EXCLUDED.usage_ar, usage_en=EXCLUDED.usage_en, image=EXCLUDED.image;