INSERT INTO public.woa_products (id, ar, en, price, category_id, usage_type, usage_ar, usage_en, image) VALUES
(431, 'ماجك سله 4/3 ارضيه خشبيه 70سم نيسكو', 'ماجك سله 4/3 ارضيه خشبيه 70cm نيسكو', '7000', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_dish_rack_lift.jpg'),
(432, 'مجرى 50سم سفلي 2 مرحلة + أمان ذاتي ساميت تركي', 'Runner/Slide 50cm سفلي 2 مرحلة + أمان ذاتي Summit Turkish', '710', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_undermount.jpg'),
(433, 'مفصله 3Dدانكو  2wayعدلة سوفت كلوز', 'Hinge 3Dدانكو  2wayStraight Soft Close', '36', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(434, 'مطبقيه استانلس لاكوست60سم', 'مطبقيه استانلس لاكوست60cm', '300', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(435, 'رجل جامبو اسود', 'رجل جامبو Black', '12', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_cabinet_legs.jpg'),
(436, 'دراع باكم mk 80 سوفت ابيض', 'Arm Hydraulic mk 80 سوفت White', '45', 4, 'other', 'أخرى', 'Other', 'assets/products/preset_gas_strut.jpg'),
(437, 'دراع باكم mk 80 سوفت اسود', 'Arm Hydraulic mk 80 سوفت Black', '45', 4, 'other', 'أخرى', 'Other', 'assets/products/preset_gas_strut.jpg'),
(438, 'مطبقيه استانلس لاكوست90سم', 'مطبقيه استانلس لاكوست90cm', '405', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(439, 'سبت عياشه تقيل', 'سبت عياشه تقيل', '65', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(440, 'مفصله مطبخ عاديه عدلة', 'Hinge مطبخ عاديه Straight', '9', 1, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_hinge_straight.jpg'),
(441, 'مفصله عقربه 2D  (MK)', 'Hinge Scorpion 2D  (MK)', '58', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(442, 'عجل دولاب سوسته 2مسمار رجلاش MK', 'عجل دولاب سوسته 2مcmار Adjustable MK', '105', 3, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_wheels.jpg'),
(443, 'باسكت2عین 40 لتر سوفتmk وحده 35', 'باسكت2عین 40 لتر سوفتmk وحده 35', '1950', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_waste_bin.jpg'),
(444, 'ترولى 20سم MK عادي', 'ترولى 20cm MK عادي', '980', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(445, 'ترولى 25سم MK عادي', 'ترولى 25cm MK عادي', '990', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(446, 'ترولى 30سم MK عادي', 'ترولى 30cm MK عادي', '1000', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(447, 'ترولى 35سم MK عادي', 'ترولى 35cm MK عادي', '1020', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(448, 'میكانیزتربیزه مقاس65 سم', 'میكانیزتربیزه مقاس65 cm', '1680', 4, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(449, 'مطبقيه 80سم ھیدرولیكmk', 'مطبقيه 80cm ھیدرولیكmk', '3650', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(450, 'طقم عجل درسنج 2ضلفه سوفت كلوز', 'طقم عجل درسنج 2ضلفه Soft Close', '675', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_wardrobe_wheels.jpg'),
(451, 'عود مجرى درسنج 3متر  لطقم 2 ضلفه', 'عود Runner/Slide درسنج 3meter  لطقم 2 ضلفه', '195', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(452, 'مسمار سن صاج ابيض خطوه واسعه 1.5 MK', 'مcmار سن صاج White خطوه واسعه 1.5 MK', '97', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(453, 'مجرى دنكو سفلیه سوفت 40سم', 'Runner/Slide دنكو سفلیه سوفت 40cm', '280', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(454, 'مجرى دنكو سفلیه سوفت 30سم', 'Runner/Slide دنكو سفلیه سوفت 30cm', '260', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_ball_bearing.jpg'),
(455, 'دولاب 5 رف 45سم سلك فضي مودرن', 'دولاب 5 Shelf 45cm Wire فضي مودرن', '4400', 7, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(456, 'رجل جامبو ابيض', 'رجل جامبو White', '12', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_cabinet_legs.jpg'),
(457, 'شماعه 80 سم ملابس ثابته جلد اورنج', 'Hanger 80 cm ملابس ثابته جلد Orange', '460', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(458, 'تكايه رف مسمار بني', 'تكايه Shelf مcmار بني', '0.5', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(459, 'تكايه رف مسمار اسود', 'تكايه Shelf مcmار Black', '0.5', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(460, 'تكايه رف مسمار بيج', 'تكايه Shelf مcmار بيج', '0.5', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(461, 'شماعه 80سم ملابس ثابته جلد جراي', 'Hanger 80cm ملابس ثابته جلد Grey', '460', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(462, 'شماعه 100سم ملابس ثابته جلد اورنج', 'Hanger 100cm ملابس ثابته جلد Orange', '480', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(463, 'شماعه 100سم ملابس ثابته جلد جراي', 'Hanger 100cm ملابس ثابته جلد Grey', '480', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(464, 'ماجيك فاصوليا 45 سم شمال مودرن', 'ماجيك فاصوليا 45 cm شمال مودرن', '3800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(465, 'ماجيك فاصوليا 45 سم يمين مودرن', 'ماجيك فاصوليا 45 cm يمين مودرن', '3800', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(466, 'درج ملابس مميز 80 سم بمجرى سفلي سوفت كلوز بالما', 'Drawer ملابس مميز 80 cm بRunner/Slide سفلي Soft Close Palma', '3850', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_undermount.jpg'),
(467, 'درج ملابس مميز 90 سم بمجرى سفلي سوفت كلوز بالما', 'Drawer ملابس مميز 90 cm بRunner/Slide سفلي Soft Close Palma', '3950', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_undermount.jpg'),
(468, 'درج ملابس مميز 70سم بمجرى سفلي سوفت كلوز بالما', 'Drawer ملابس مميز 70cm بRunner/Slide سفلي Soft Close Palma', '3750', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_undermount.jpg'),
(469, 'مسمار اليتا مشترك', 'مcmار اليتا مشترك', '15', 5, 'other', 'أخرى', 'Other', 'assets/products/preset_fasteners_screws.jpg'),
(470, 'رشاقه باكم نانو 80سم', 'رشاقه Hydraulic نانو 80cm', '4900', 4, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_gas_strut.jpg'),
(471, 'مقبض بلت ان هوك 100 سم مستورد جديد اسود', 'Handle بلت ان هوك 100 cm مستورد جديد Black', '150', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(472, 'مقبض G بلت ان 100 سم مستورد جديد اسود', 'Handle G بلت ان 100 cm مستورد جديد Black', '170', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(473, 'مقبض G بلت ان 100 سم مستورد جديد دهبي', 'Handle G بلت ان 100 cm مستورد جديد دهبي', '170', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(474, 'مقبض مسطره 100سم اسود', 'Handle مسطره 100cm Black', '160', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(475, 'رجل نجمه اسود 10سم', 'رجل نجمه Black 10cm', '28', 9, 'other', 'أخرى', 'Other', 'assets/products/preset_cabinet_legs.jpg'),
(476, 'مقبض ماسورة 160اسود جديد', 'Handle ماسورة 160Black جديد', '17', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(477, 'مقبض ماسورة 128اسود جديد', 'Handle ماسورة 128Black جديد', '15', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(478, 'مقبض ماسورة 96اسود جديد', 'Handle ماسورة 96Black جديد', '13', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(479, 'مقبض دهبي مسطره 30سم G', 'Handle دهبي مسطره 30cm G', '50', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(480, 'زرار مدور دهبي', 'زرار مدور دهبي', '12', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(481, 'زرار مربع اسود', 'زرار مربع Black', '12', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(482, 'زرار مربع دهبي', 'زرار مربع دهبي', '12', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_general_hardware.jpg'),
(483, 'مقبض G بلت ان 40سم مستورد جديد دهبي', 'Handle G بلت ان 40cm مستورد جديد دهبي', '55', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(484, 'مقبض G بلت ان 25 سم مستورد جديد دهبي', 'Handle G بلت ان 25 cm مستورد جديد دهبي', '45', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(485, 'مقبض G بلت ان 40 سم مستورد جديد اسود', 'Handle G بلت ان 40 cm مستورد جديد Black', '55', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(486, 'مقبض G بلت ان 20 سم مستورد جديد اسود', 'Handle G بلت ان 20 cm مستورد جديد Black', '29', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(487, 'مقبض فيونكه اسود *دهبي 96', 'Handle فيونكه Black *دهبي 96', '16', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(488, 'مقبض فيونكه اسود *دهبي 128', 'Handle فيونكه Black *دهبي 128', '17', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_black.jpg'),
(489, 'مقبض فيونكه دهبي *دهبي 128', 'Handle فيونكه دهبي *دهبي 128', '17', 2, 'other', 'أخرى', 'Other', 'assets/products/preset_handle_bar_silver.jpg'),
(490, 'مفصله عقربه 155سوفت كلوز  3D بالما', 'Hinge Scorpion 155Soft Close  3D Palma', '97', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(491, 'مجرى درج 50سم تاندم بوكس ارتفاع  84 مم palma', 'Runner/Slide Drawer 50cm تاندم بوكس ارتفاع  84 مم palma', '1020', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_tandem.jpg'),
(492, 'مجرى درج 50سم تاندم بوكس ارتفاع 167 مم palma', 'Runner/Slide Drawer 50cm تاندم بوكس ارتفاع 167 مم palma', '1180', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_tandem.jpg'),
(493, 'مجرى درج 50سم تاندم بوكس ارتفاع  116 مم palma', 'Runner/Slide Drawer 50cm تاندم بوكس ارتفاع  116 مم palma', '1100', 3, 'other', 'أخرى', 'Other', 'assets/products/preset_drawer_tandem.jpg'),
(494, 'دولاب محوري 6رف استانلس 45سم فضي بالما سوفت كلوز', 'دولاب محوري 6Shelf استانلس 45cm فضي Palma Soft Close', '8100', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_general_hardware.jpg'),
(495, 'ترولي مودرن سوفت كلوز 35سم', 'ترولي مودرن Soft Close 35cm', '1700', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(496, 'مفصله عقربه 3D  دانكو', 'Hinge Scorpion 3D  دانكو', '85', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(497, 'مفصله كاف عدلة سوفت كلوز 3D', 'Hinge كاف Straight Soft Close 3D', '44', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(498, 'مفصله كاف نص ركبة سوفت كلوز 3D', 'Hinge كاف Half Overlay Soft Close 3D', '44', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(499, 'مفصله كاف ركبة  سوفت كلوز 3D', 'Hinge كاف ركبة  Soft Close 3D', '44', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(500, 'مفصله كاف عدلة سوفت كلوز 4D', 'Hinge كاف Straight Soft Close 4D', '49', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(501, 'مفصله كاف عدلة سوفت كلوز 2D', 'Hinge كاف Straight Soft Close 2D', '28', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_straight.jpg'),
(502, 'مفصله كاف نص ركبة سوفت كلوز 2D', 'Hinge كاف Half Overlay Soft Close 2D', '28', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(503, 'مفصله كاف ركبة سوفت كلوز 2D', 'Hinge كاف ركبة Soft Close 2D', '28', 1, 'other', 'أخرى', 'Other', 'assets/products/preset_hinge_crank.jpg'),
(504, 'رشاقه باكم نانو 70سم', 'رشاقه Hydraulic نانو 70cm', '4700', 4, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_gas_strut.jpg'),
(505, 'رشاقه باكم نانو 90سم', 'رشاقه Hydraulic نانو 90cm', '5400', 4, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_gas_strut.jpg'),
(506, 'جزامة محورية 8رف نيسكو', 'جزامة محورية 8Shelf نيسكو', '15000', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_general_hardware.jpg'),
(507, 'شماعه بناطيل جانبيه مضئه نيسكو', 'Hanger بناطيل جانبيه مضئه نيسكو', '3900', 7, 'dressing', 'دريسينج', 'Dressing', 'assets/products/preset_wardrobe_accessories.jpg'),
(508, 'مرايا مضيئه نيسكو', 'مرايا مضيئه نيسكو', '5000', 10, 'other', 'أخرى', 'Other', 'assets/products/preset_wardrobe_accessories.jpg'),
(509, 'ترولي زجاجي الماني 30سم نيسكو', 'ترولي زجاجي الماني 30cm نيسكو', '4200', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg'),
(510, 'ترولي زجاجي الماني 35سم نيسكو', 'ترولي زجاجي الماني 35cm نيسكو', '4300', 7, 'kitchen', 'مطابخ', 'Kitchen', 'assets/products/preset_dish_rack_lift.jpg')
ON CONFLICT (id) DO UPDATE SET ar=EXCLUDED.ar, en=EXCLUDED.en, price=EXCLUDED.price, category_id=EXCLUDED.category_id, usage_type=EXCLUDED.usage_type, usage_ar=EXCLUDED.usage_ar, usage_en=EXCLUDED.usage_en, image=EXCLUDED.image;